/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrescriptionRouteImport } from './routes/prescription'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MedicinesRouteImport } from './routes/medicines'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LabTestsRouteImport } from './routes/lab-tests'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as HealthRecordsRouteImport } from './routes/health-records'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as CircleRouteImport } from './routes/circle'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionRoute = PrescriptionRouteImport.update({
  id: '/prescription',
  path: '/prescription',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicinesRoute = MedicinesRouteImport.update({
  id: '/medicines',
  path: '/medicines',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LabTestsRoute = LabTestsRouteImport.update({
  id: '/lab-tests',
  path: '/lab-tests',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRecordsRoute = HealthRecordsRouteImport.update({
  id: '/health-records',
  path: '/health-records',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const CircleRoute = CircleRouteImport.update({
  id: '/circle',
  path: '/circle',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/circle': typeof CircleRoute
  '/doctors': typeof DoctorsRoute
  '/health-records': typeof HealthRecordsRoute
  '/insurance': typeof InsuranceRoute
  '/lab-tests': typeof LabTestsRoute
  '/login': typeof LoginRoute
  '/medicines': typeof MedicinesRoute
  '/orders': typeof OrdersRoute
  '/prescription': typeof PrescriptionRoute
  '/profile': typeof ProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/circle': typeof CircleRoute
  '/doctors': typeof DoctorsRoute
  '/health-records': typeof HealthRecordsRoute
  '/insurance': typeof InsuranceRoute
  '/lab-tests': typeof LabTestsRoute
  '/login': typeof LoginRoute
  '/medicines': typeof MedicinesRoute
  '/orders': typeof OrdersRoute
  '/prescription': typeof PrescriptionRoute
  '/profile': typeof ProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/circle': typeof CircleRoute
  '/doctors': typeof DoctorsRoute
  '/health-records': typeof HealthRecordsRoute
  '/insurance': typeof InsuranceRoute
  '/lab-tests': typeof LabTestsRoute
  '/login': typeof LoginRoute
  '/medicines': typeof MedicinesRoute
  '/orders': typeof OrdersRoute
  '/prescription': typeof PrescriptionRoute
  '/profile': typeof ProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/circle'
    | '/doctors'
    | '/health-records'
    | '/insurance'
    | '/lab-tests'
    | '/login'
    | '/medicines'
    | '/orders'
    | '/prescription'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/circle'
    | '/doctors'
    | '/health-records'
    | '/insurance'
    | '/lab-tests'
    | '/login'
    | '/medicines'
    | '/orders'
    | '/prescription'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/circle'
    | '/doctors'
    | '/health-records'
    | '/insurance'
    | '/lab-tests'
    | '/login'
    | '/medicines'
    | '/orders'
    | '/prescription'
    | '/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CircleRoute: typeof CircleRoute
  DoctorsRoute: typeof DoctorsRoute
  HealthRecordsRoute: typeof HealthRecordsRoute
  InsuranceRoute: typeof InsuranceRoute
  LabTestsRoute: typeof LabTestsRoute
  LoginRoute: typeof LoginRoute
  MedicinesRoute: typeof MedicinesRoute
  OrdersRoute: typeof OrdersRoute
  PrescriptionRoute: typeof PrescriptionRoute
  ProfileRoute: typeof ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescription': {
      id: '/prescription'
      path: '/prescription'
      fullPath: '/prescription'
      preLoaderRoute: typeof PrescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicines': {
      id: '/medicines'
      path: '/medicines'
      fullPath: '/medicines'
      preLoaderRoute: typeof MedicinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab-tests': {
      id: '/lab-tests'
      path: '/lab-tests'
      fullPath: '/lab-tests'
      preLoaderRoute: typeof LabTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-records': {
      id: '/health-records'
      path: '/health-records'
      fullPath: '/health-records'
      preLoaderRoute: typeof HealthRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circle': {
      id: '/circle'
      path: '/circle'
      fullPath: '/circle'
      preLoaderRoute: typeof CircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CircleRoute: CircleRoute,
  DoctorsRoute: DoctorsRoute,
  HealthRecordsRoute: HealthRecordsRoute,
  InsuranceRoute: InsuranceRoute,
  LabTestsRoute: LabTestsRoute,
  LoginRoute: LoginRoute,
  MedicinesRoute: MedicinesRoute,
  OrdersRoute: OrdersRoute,
  PrescriptionRoute: PrescriptionRoute,
  ProfileRoute: ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
